### ISSUE TITLE
Dealing with confounding features

### ISSUE THREAD

**Issue by azhylka** [oeminaga/AI_PCA_GRADE#4]
Dear Dr. Eminaga, 

I came across your paper on predicting prostate cancer recurrence from slides: https://doi.org/10.1038/s44303-023-00005-z, which I think addresses very important challenges that are common not only for histopathology. So, I hope you could answer some of my questions.

As far as I understand you had to find a solution to deal with pen marks in both training and testing data. Generally, the pen marks can be a confounding feature, so I was wondering how you addressed that.
I am also curious if you found correlations of the marks with survival in your work. 
And did you compare model performance on slides with and without pen marks, or simply exclude the slides with pen marks from test?

With best regards,
Andrey

**Comment by oeminaga** [comment]
Dear Andrey,

Thank you so much for your comment. I'm sorry for the delay in getting back to you; I've been caught up with a few other responsibilities.

Yes, you're absolutely right about the pen mark artifact being a confounder. During the study, we did test the prediction on patches with pure pen mark artifacts and found that they had a prediction score of around 0. While the TMA cores had no pen marks, the WSIs did include such artifacts. So, when we manually delineated the tumor area, we kept a considerable buffer distance from the pen mark fields to minimize the chances of patches with artifacts being included in the analysis. Our examination of patches originating from the delineated areas in 50 WSIs revealed that the patches with pen mark artifacts were negligible, making up roughly only 1 - 2%, indicating that the delineation strategy is sufficient.

Despite this strategy, we recognize a potential drawback in missing patches containing information on the boundary of the pen marks. However, in our specific scenario, prioritizing patch quality over patch quantity was crucial for establishing a robust prediction model. Additionally, it's important to mention that pathologists typically refrain from assessing spots with artifacts when clearer alternatives are accessible.

Once again, thank you for your valuable input, Andrey. If you have any further questions or suggestions, please feel free to share them.

With warmth regards,

Okyaz
